### PR TITLE
Bump ES and Chrome target versions to reflect actual code

### LINKED ISSUE #716: 04369be error TS1501: This regular expression flag is only available when targeting 'es2018' or later.
### Steps to reproduce

1. Clone https://github.com/FreeTubeApp/FreeTube
2. Install youtubei.js from git: 
    "youtubei.js": "git+https://github.com/LuanRT/YouTube.js.git"
3. Run `yarn` to install new version of youtubei.js

### Failure Logs

```shell
$ npm run build

> youtubei.js@10.2.0 build
> npm run clean && npm run build:parser-map && npm run build:proto && npm run build:esm && npm run bundle:node && npm run bundle:browser && npm run bundle:browser:prod && npm run bundle:cf-worker && npm run bundle:react-native


> youtubei.js@10.2.0 clean
> npx rimraf ./dist/src ./dist/package.json ./bundle/browser.js ./bundle/browser.js.map ./bundle/browser.min.js ./bundle/browser.min.js.map ./bundle/node.cjs ./bundle/node.cjs.map ./bundle/cf-worker.js ./bundle/cf-worker.js.map ./bundle/react-native.js ./bundle/react-native.js.map ./deno


> youtubei.js@10.2.0 build:parser-map
> node ./dev-scripts/gen-parser-map.mjs


> youtubei.js@10.2.0 build:proto
> npx pb-gen-ts --entry-path="src/proto" --out-dir="src/proto/generated" --ext-in-import=".js"


> youtubei.js@10.2.0 build:esm
> npx tspc

src/core/Player.ts:224:185 - error TS1501: This regular expression flag is only available when targeting 'es2018' or later.

224     const match = data.match(/b=(?:a\.split\(|String\.prototype\.split\.call\(a,)\n?(?:""|\("",""\))\).*?\}return (?:b\.join\(|Array\.prototype\.join\.call\(b,)\n?(?:""|\("",""\))\)\}/s);
                                                                                                                                                                                            ~


Found 1 error in src/core/Player.ts:224
```

### Expected behavior

The esm build succeeds.

### Current behavior

The esm build fails.

### Version

Default

### Anything else?

Suggest changing tsconfig.json to target es2018

Change that broke build: https://github.com/LuanRT/YouTube.js/commit/04369be620e452ab3c4b2d14991fc55773995137

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

### PR DESCRIPTION
**Pull request by darktohka**
Fixes #716 and #717.

The ES target version is bumped to es2018 to support the new regex that was introduced in https://github.com/LuanRT/YouTube.js/commit/04369be620e452ab3c4b2d14991fc55773995137.

The browser target version is bumped to chrome63 to support the async generators used since fb68e6bc.

### CODE REVIEW

**Review by rogerpadilla — APPROVED** [review]
LGTM. Only thing is there are failing unit tests.

**Comment by LuanRT** [comment]
I just updated these values while working on something unrelated, so I'll close this one as it's no longer needed. But thank you for the PR, it's always appreciated.
