### ISSUE TITLE
10.x.x Deno jintr package version not specified.

### ISSUE THREAD

**Issue by Redcrafter** [LuanRT/YouTube.js#767]
### Steps to reproduce

Creating a new client using `await Innertube.create()` fails.

### Failure Logs

```shell
error: Uncaught (in promise) TypeError: Jinter.parseScript is not a function
  const node = Jinter.parseScript(source);
                      ^
    at findFunction (https://deno.land/x/youtubei@v10.5.0-deno/deno/src/utils/Utils.ts:291:23)
    at Function.extractNSigSourceCode (https://deno.land/x/youtubei@v10.5.0-deno/deno/src/core/Player.ts:238:27)
    at Function.create (https://deno.land/x/youtubei@v10.5.0-deno/deno/src/core/Player.ts:68:26)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async Function.create (https://deno.land/x/youtubei@v10.5.0-deno/deno/src/core/Session.ts:278:55)
    at async Function.create (https://deno.land/x/youtubei@v10.5.0-deno/deno/src/Innertube.ts:64:26)
```

### Expected behavior

The client is created successfully.

### Current behavior

The client is not created.

### Version

Default

### Anything else?

When importing a package without specifying the version deno will use older versions if they have been previously cached. As such it defaulted to https://esm.sh/jintr@1.1.0 after i updated from 9.4.0 to 10.5.0 which causes the error.
See https://deno.land/x/youtubei@v10.5.0-deno/deno/src/utils/Utils.ts?source=#L5

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.
