### PR TITLE
fix: fix deno usage of protobuf and jintr

### LINKED ISSUE #766: 10.5.0 Deno missing @bufbuild/protobuf import
### Steps to reproduce

Trying to install the 10.5.0 deno package produces an error.

### Failure Logs

```shell
error: Relative import path "@bufbuild/protobuf/wire" not prefixed with / or ./ or ../ and not in import map from "https://deno.land/x/youtubei@v10.5.0-deno/deno/protos/generated/misc/params.ts"
    at https://deno.land/x/youtubei@v10.5.0-deno/deno/protos/generated/misc/params.ts:8:44
```

### Expected behavior

The package is installed without errors.

### Current behavior

The package cannot be installed.

### Version

Default

### Anything else?

The @bufbuild/protobuf package is not specified anywhere so it can't be found.
As a temporary fix you can add `"@bufbuild/protobuf": "npm:@bufbuild/protobuf"` to the import list.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

### LINKED ISSUE #767: 10.x.x Deno jintr package version not specified.
### Steps to reproduce

Creating a new client using `await Innertube.create()` fails.

### Failure Logs

```shell
error: Uncaught (in promise) TypeError: Jinter.parseScript is not a function
  const node = Jinter.parseScript(source);
                      ^
    at findFunction (https://deno.land/x/youtubei@v10.5.0-deno/deno/src/utils/Utils.ts:291:23)
    at Function.extractNSigSourceCode (https://deno.land/x/youtubei@v10.5.0-deno/deno/src/core/Player.ts:238:27)
    at Function.create (https://deno.land/x/youtubei@v10.5.0-deno/deno/src/core/Player.ts:68:26)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async Function.create (https://deno.land/x/youtubei@v10.5.0-deno/deno/src/core/Session.ts:278:55)
    at async Function.create (https://deno.land/x/youtubei@v10.5.0-deno/deno/src/Innertube.ts:64:26)
```

### Expected behavior

The client is created successfully.

### Current behavior

The client is not created.

### Version

Default

### Anything else?

When importing a package without specifying the version deno will use older versions if they have been previously cached. As such it defaulted to https://esm.sh/jintr@1.1.0 after i updated from 9.4.0 to 10.5.0 which causes the error.
See https://deno.land/x/youtubei@v10.5.0-deno/deno/src/utils/Utils.ts?source=#L5

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

### PR DESCRIPTION
**Pull request by unixfox**
Replace these lines at build time for deno:
```
import { Jinter } from 'jintr';
```
to:
```
import { Jinter } from 'https://esm.sh/jintr@2.1.1';
```

and
```
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
```
to:
```
import { BinaryReader, BinaryWriter } from "https://esm.sh/@bufbuild/protobuf@2.0.0";
```

Everytime one of these two lib is updated in the package.json, these should also be updated in the "build:deno" command: https://github.com/LuanRT/YouTube.js/blob/5ff30e12ded29afff5a758cbe96ac3418e6d20aa/package.json#L84

----

Also fixes this warning (Deno V1) and now an error in Deno V2:
```
error: Import assertions are deprecated. Use `with` keyword, instead of 'assert' keyword.

import package_json from '../../package.json' assert { type: 'json' };
```

----

Closes #767 
Closes #766

### CODE REVIEW

**Review by LuanRT — APPROVED** [review]

**Comment by unixfox** [comment]
deno compile is failing though :/. will see what I can do about it
