### ISSUE TITLE
jintr 3.3.1 buiold issue issue

### ISSUE THREAD

**Issue by geitir** [LuanRT/YouTube.js#1049]
### Steps to reproduce

Hi when updating to v15 and npm building ESM with ES2022 and Node16 I am getting 

`
node_modules/jintr/dist/main.d.ts:2:8 - error TS1192: Module '".../node_modules/acorn/dist/acorn"' has no default export.
import acorn from 'acorn';
`

Which is resolved when downgrade jintr  to 3.2.1

### Failure Logs

```shell
N/A
```

### Expected behavior

Works

### Current behavior

Doesn't

### Version

Default

### Checklist

- [x] I am running the latest version.
- [x] I checked the documentation and found no answer.
- [x] I have searched the existing issues and made sure this is not a duplicate.
- [x] I have provided sufficient information.

**Comment by absidue** [comment]
While the error is valid, you should also be using Node.js 20.10+ with YouTube.js 15.

**Comment by absidue** [comment]
Closing as jintr is no longer used in more recent versions.
